const API_BASE_URL = "http://127.0.0.1:3500/api";
const APP_BASE_URI = "";

const ADMIN_LAYOUT_SUFFIX = "admin";
const LOGIN_LAYOUT_SUFFIX = "login";
const SIGNUP_LAYOUT_SUFFIX = "signup";
const SIGNUP_UPDATE_SUFFIX = "update/:id";

const GET_USERS_URL = `${API_BASE_URL}/users`;
const UPDATE_USER_URL = `${API_BASE_URL}/users/:id`;

export const environment = {
  production: false,
  
  BASE_URL: APP_BASE_URI,

  UPDATE_SUFFIX: SIGNUP_UPDATE_SUFFIX,
  ADMIN_SUFFIX: ADMIN_LAYOUT_SUFFIX,
  LOGIN_SUFFIX: LOGIN_LAYOUT_SUFFIX,
  SIGNUP_SUFFIX: SIGNUP_LAYOUT_SUFFIX,
  
  FETCH_USERS_URL: GET_USERS_URL,
  USER_UPDATE_URL: UPDATE_USER_URL,
};
